import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import IdleLogout from "../components/idlelogout"; // 👈 tambahkan

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-poppins",
});

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Psychotest App",
  description: "Generated by create next app",
  icons: {
    icon: "/logoklinik.png",
    shortcut: "/logoklinik.png",
    apple: "/logoklinik.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${geistSans.variable} ${geistMono.variable}`}
    >
      <body className="antialiased">
        <IdleLogout />   {/* 👈 Idle logout aktif global */}
        {children}
      </body>
    </html>
  );
}
