import type { Metadata } from "next";
import { poppins, geistSans, geistMono } from "./font";
import "./globals.css";
import IdleLogout from "../components/idlelogout";

export const metadata: Metadata = {
  title: "Psychotest App",
  description: "Generated by create next app",
  icons: {
    icon: "/logoklinik.png",
    shortcut: "/logoklinik.png",
    apple: "/logoklinik.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${geistSans.variable} ${geistMono.variable}`}
    >
      <body className="antialiased">
        <IdleLogout />
        {children}
      </body>
    </html>
  );
}
